### ISSUE TITLE
3.8.2: ld duplicate symbols building for tests on device on Xcode 6.4

### ISSUE THREAD

**Issue by fcy** [bitstadium/HockeySDK-iOS#211]
I'm getting the exact same problem as in https://github.com/bitstadium/HockeySDK-iOS/issues/190 but using version 3.8.2 which should support Xcode 6.4 according to https://github.com/bitstadium/HockeySDK-iOS/issues/199.

Only happens when building for tests on a real device.

**Comment by lumaxis** [comment]
I can only reproduce this issue when also linking HockeySDK with our demo app's test target, if I remove that it works fine with Xcode 6.4 here. Are you also using CocoaPods to integrate the SDK? If so, can you double check your Podfile and let me know if that helps? Thanks!

**Comment by fcy** [comment]
Yes, I'm using CocoaPods 0.39.0. My `Podfile` looks like this (I've omit all other pods):

```
target "AppTarget" do
    pod 'HockeySDK', '~> 3.7', inhibit_warnings: true
end

target "Tests", exclusive: true do
    pod 'Kiwi', '~> 2.0'
end
```

And I checked the `Podfile.lock` to make sure there is no indirect dependency:

```
$ cat Podfile.lock | grep HockeySDK
  - HockeySDK (3.8.2):
    - HockeySDK/AllFeaturesLib (= 3.8.2)
  - HockeySDK/AllFeaturesLib (3.8.2)
  - HockeySDK (~> 3.7)
  HockeySDK: 9f4ac41263acf9d8a4d59491a7f17af16529b935
```

Any other ideas I could try?

**Comment by lumaxis** [comment]
My only idea right now would be to try removing and re-adding everything CocoaPods related except your Podfile to make sure it's not some sort of caching issue.
If that also doesn't help, it'd be awesome if you can manage to reproduce the issue in a simple sample project that we could then take a look at.
